services:
  partita-bot:
    image: ghcr.io/lucanori/partita-bot:latest
    container_name: partita-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=bot
      - BOT_COMMAND=python run_bot.py
    labels:
      # Enable Watchtower, remove if not needed
      - com.centurylinklabs.watchtower.enable=true
  
  partita-admin:
    image: ghcr.io/lucanori/partita-bot:latest
    container_name: partita-admin
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=admin
      - ADMIN_COMMAND=gunicorn --bind 0.0.0.0:${ADMIN_PORT:-5000} --access-logfile - --error-logfile - wsgi:application
    labels:
      # Enable Watchtower, remove if not needed
      - com.centurylinklabs.watchtower.enable=true