services:
  partita-bot:
    build: .
    container_name: partita-bot-local
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=bot
      - BOT_COMMAND=python run_bot.py
  
  partita-admin:
    build: .
    container_name: partita-admin-local
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - SERVICE_TYPE=admin
      - ADMIN_COMMAND=gunicorn --bind 0.0.0.0:${ADMIN_PORT:-5000} --access-logfile - --error-logfile - wsgi:application