services:
  partita-bot:
    build: .
    container_name: partita-bot-local
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env