name: Docker

on:
  push:
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set repository name to lowercase
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update TUF metadata
        run: |
          # Attempt to update local TUF metadata; ignore errors if this fails.
          tuf client update || true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}:${{ github.ref_name }},ghcr.io/${{ env.REPO_LOWER }}:latest

      - name: Sign the Docker image
        run: |
          # Replace <your-key> with the secret (e.g., COSIGN_KEY) or adjust the command to use OIDC if preferred.
          cosign sign --key ${{ secrets.COSIGN_KEY }} ghcr.io/${{ env.REPO_LOWER }}:${{ github.ref_name }}