name: Docker

# Only trigger on version tags
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    # Add permissions at job level
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set repository name to lowercase
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }}
            ghcr.io/${{ env.REPO_NAME }}:latest

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }}